export const primaryBlue = '#589CFE';
export const primaryLightBlue = '#1BD2F8';
export const primaryBlack = '#45535C';
export const primaryGrey = '#00000040';
export const formFieldGrey = '#647F9A';
export const lightGray = '#DBE1EC';
export const lightGrayBackround = '#F2F0FE';
export const inputBorder = '#87A1BB';
export const green = '#15C5AE';
export const lightGreen = '#17D2B9';
export const primaryWhite = '#FFFFFF';
export const lightBlue = '#E5EDF5';
export const lightRed = '#FD767A';
export const purple = '#8C99FF';
export const borderGrey = '#E9EAF3';
export const disable = '#FDFEFE ';
export const backgroundGreen = '#EDF9F6';
export const backgroundGrey = '#F5F6FA';
export const circleBorder = '#D8E1F1';
export const circleBackground = '#F4F6FA';
export const backgroundBlue = '#F5F8FA';
export const red = '#F86060';
export const backgroudLightGrey = '#F5F6FB';
export const aliceBlue = '#ECF4FE';
export const lighBlack = '#7692AE';
export const lightGrayBorder = '#CED0D4';
export const backgroundligthBlue = '#589CFE12';
export const backgroudLightGreen = '#F0FAF7';
export const backgroudGreen = '#05D6A7';
export const backgroudWhiteShadeGray = '#FDFEFE';
export const darkBlue = '#3378DB';
export const backgroudGrayVeryLight = '#F6F6F7';
export const iconBackgroundLightBlue = "#F3F9FE";
export const backgroudLightRed = '#f860601a';
export const lightGrayishBlue = "#BFC9DE"
export const lightPeriwinkle = "#BFC9DEDE"
export const paleCornflowerBlue = "#ACCEFF"
export const gardenGlow = "#7FC897"
export const plaster = "#EAEAEA"
export const shadowPrimaryBlue = "#589cfe4d"
export const wildBlueYonder = "#9DB3C9"
export const ghostWhite = "#F8FAFE"
export const lightSteelBlue = "#B5C8DA"
export const columbiaBlue = "#CED8EB"
export const platinum = "#DEE2EA"
export const aliceBlueBackground = "#F4F7FB"
export const readedGreen = "#27AE60"
export const rajah = "#F8A960"
export const mediumSeaGreen = "#3AA76D"
export const cloudBlue = "#CFE1FB"
export const lightPeriwinkles = "#BEC8DD"
export const cornflowerBlue = "#589cfe4d"
export const robinEggBlue = "#ABCDFE"
export const transparentBlack = "rgba(0,0,0,0.3)"
export const lightTransparentBlack = "rgba(0,0,0,0.1)"
export const workoutBlue = "#F0F6FE"
export const robinEggBlueWithOpacity = "rgba(171,205,254,0.7)"
export const chatSearchBorder = "#ADB5C7";
export const chatBarTextBlack = "#212633";
export const chatBarBack = "rgba(171, 205, 254, 0.3)";
export const strokeGray = "rgba(60, 60, 67, 0.36)";
export const textLightGray = "#B9C3D7";
export const lightChatBlue = "rgba(88, 156, 254, 0.4)";
export const lightLine = "rgba(185, 195, 215, 0.2)";
export const darkWhite = "#F6F6F9";
export const boldBlack = "rgba(52, 52, 52, 1)";
export const assistantMessageBlack = "rgba(8, 8, 10, 1)";
export const midGray = "#989FC9";
export const opacityBlack = "rgba(0,0,0,0.8)";
